# Build stage
FROM node:latest as build
WORKDIR /app

ARG VITE_SESSION_URL
ARG VITE_CLIENT_ID
ENV VITE_SESSION_URL=$VITE_SESSION_URL
ENV VITE_CLIENT_ID=$VITE_CLIENT_ID

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Serve with Nginx
FROM nginx:latest
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html